plugins:
- '@semantic-release/commit-analyzer'
- '@semantic-release/release-notes-generator'
- '@semantic-release/changelog'
  # - - "@semantic-release/git"
  #   - assets:
  #     - CHANGELOG.md
  #     message: "chore(release): version ${nextRelease.version}\n\n${nextRelease.notes}"
- '@semantic-release/github'
branches:
- master
- +([0-9])?(.{+([0-9]),x}).x
